-- Trip Planner — Supabase schema for the Benefits, Credits & Expirations
-- Tracker. Run once in the SQL Editor (after schema.sql).
--
-- One row per user holding a JSONB:
--   { cards: [{id,name,fee,renewalDate,remind,credits:[{id,label,amount,
--       cadence,usedAmount,resetDate,remind}]}],
--     perks: [{id,kind,label,expiresOn,cap,note,remind}],
--     pointsExpirations: [{id,program,expiresOn,note,remind}] }
--
-- Deadline push reminders are plain `watchers` rows of type 'benefit',
-- regenerated by the client on every save — the existing watcher-run cron
-- delivers them (web push + Expo push) with no edge-function changes.

create table if not exists public.benefits (
  user_id    uuid primary key references auth.users (id) on delete cascade,
  data       jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.benefits enable row level security;

drop policy if exists "Users read own benefits"   on public.benefits;
drop policy if exists "Users insert own benefits" on public.benefits;
drop policy if exists "Users update own benefits" on public.benefits;
drop policy if exists "Users delete own benefits" on public.benefits;

create policy "Users read own benefits"
  on public.benefits for select
  using (auth.uid() = user_id);

create policy "Users insert own benefits"
  on public.benefits for insert
  with check (auth.uid() = user_id);

create policy "Users update own benefits"
  on public.benefits for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users delete own benefits"
  on public.benefits for delete
  using (auth.uid() = user_id);
