// Destination cheat sheet: a per-trip "know before you go" guide generated by
// the destination-guide Edge Function (Claude Haiku, quota-guarded) and cached
// on the trip JSONB (trip.guide), so it is generated once per trip unless the
// destinations change or the user refreshes.
//
// PRIVACY: the request carries only the trip's destination list + dates + an
// OPTIONAL passport-country string typed here. Nothing is read from the vault,
// and trip.guide is not part of share-trip snapshots (share.js cherry-picks).
import { supabase } from './supabase.js';
import { activeTrip } from './state.js';
import { save, markTripDirty } from './storage.js';
import { el } from './dom.js';

const LAST_PASSPORT_KEY = 'vacation_planner_guide_passport';

function hash(s) {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return h.toString(36);
}

// The destination list the guide is about: cities from scheduled/library cards
// plus saved places' cities. Deduped, order-stable.
function tripPlaces(t) {
  const seen = new Set();
  const out = [];
  const add = v => {
    const s = (v || '').trim();
    if (!s) return;
    const k = s.toLowerCase();
    if (seen.has(k)) return;
    seen.add(k);
    out.push(s);
  };
  Object.values(t.cards || {}).forEach(c => {
    add(c.city);
    add(c.originCity);
    add(c.destCity);
  });
  (t.places || []).forEach(p => add(p.city));
  return out.slice(0, 40);
}

function guideKey(t, places) {
  return hash(JSON.stringify([places, t.startDate, t.endDate]));
}

const SECTIONS = [
  ['entry', 'Entry & visa', 'ti-passport'],
  ['health', 'Health & water', 'ti-vaccine'],
  ['money', 'Money & tipping', 'ti-coins'],
  ['power', 'Plugs & power', 'ti-plug'],
  ['emergency', 'Emergency numbers', 'ti-urgent'],
  ['transit', 'Getting around', 'ti-bus'],
  ['weather', 'Weather for your dates', 'ti-cloud'],
  ['phrases', 'Key phrases', 'ti-language'],
];

function renderGuides(body, t, places) {
  const g = t.guide;
  body.innerHTML = '';

  if (guideKey(t, places) !== g.key) {
    body.appendChild(el('div', { class: 'vp-dg-stale' },
      el('i', { class: 'ti ti-refresh-alert' }),
      ' Your destinations or dates changed since this guide was made — refresh it below.'));
  }

  (g.guides || []).forEach(guide => {
    body.appendChild(el('h4', { class: 'vp-dg-dest' }, guide.destination));
    SECTIONS.forEach(([k, title, icon]) => {
      if (!guide[k]) return;
      const sec = el('div', { class: 'vp-dg-sec' });
      sec.appendChild(el('div', { class: 'vp-dg-sec-head' },
        el('i', { class: 'ti ' + icon }), el('span', {}, title)));
      sec.appendChild(el('div', { class: 'vp-dg-sec-body' }, guide[k]));
      body.appendChild(sec);
    });
  });

  body.appendChild(el('p', { class: 'vp-dg-disclaimer' },
    'AI-generated guidance' + (g.passportCountry ? ' for ' + g.passportCountry + ' passport holders' : '') +
    (g.generatedAt ? ', made ' + new Date(g.generatedAt).toLocaleDateString() : '') +
    '. Always verify visa, entry, and health rules with official sources before you travel.'));
}

async function generate(t, places, passportCountry) {
  let res;
  try {
    res = await supabase.functions.invoke('destination-guide', {
      body: {
        places,
        startDate: t.startDate || '',
        endDate: t.endDate || '',
        passportCountry: passportCountry || '',
      },
    });
  } catch {
    throw new Error('Could not reach the destination-guide service.');
  }
  if (res.error) throw new Error('The destination-guide service failed.');
  const data = res.data;
  if (!data || data.ok !== true) throw new Error((data && data.error) || 'Guide generation failed.');
  const guides = Array.isArray(data.guides) ? data.guides : [];
  if (!guides.length) throw new Error('The AI could not produce a guide for these destinations.');

  t.guide = {
    generatedAt: new Date().toISOString(),
    key: guideKey(t, places),
    passportCountry: passportCountry || '',
    guides,
  };
  markTripDirty(t.id);
  save();
}

function renderGenerateForm(body, t, places, isRefresh) {
  const form = el('div', { class: 'vp-dg-form' });
  form.appendChild(el('p', { class: 'vp-profile-sub' },
    'A cheat sheet for ' + places.slice(0, 6).join(', ') + (places.length > 6 ? '…' : '') +
    ' — entry rules, plugs, tipping, emergency numbers, transit, weather for your dates, and key phrases.'));

  let lastPassport = '';
  try { lastPassport = localStorage.getItem(LAST_PASSPORT_KEY) || ''; } catch { /* ignore */ }
  const passport = el('input', {
    type: 'text',
    value: (t.guide && t.guide.passportCountry) || lastPassport,
    placeholder: 'e.g. United States',
  });
  const prow = el('div', { class: 'vp-profile-row' });
  prow.appendChild(el('label', {}, 'Passport country (optional — sharpens the visa info)'));
  prow.appendChild(passport);
  form.appendChild(prow);

  const status = el('div', { class: 'vp-dg-status' });
  const btn = el('button', { class: 'vp-save' }, isRefresh ? 'Refresh guide' : 'Generate guide');
  btn.addEventListener('click', async () => {
    btn.disabled = true;
    status.textContent = 'Writing your guide… (10–20 seconds)';
    try {
      const pc = passport.value.trim();
      try { localStorage.setItem(LAST_PASSPORT_KEY, pc); } catch { /* ignore */ }
      await generate(t, places, pc);
      renderOpen(body, t);
    } catch (e) {
      status.textContent = e.message || 'Something went wrong.';
      status.classList.add('vp-dg-status-err');
      btn.disabled = false;
    }
  });
  form.appendChild(btn);
  form.appendChild(status);
  body.appendChild(form);
}

// Top-level body render: cached guide (+ refresh form below) or just the form.
function renderOpen(body, t) {
  const places = tripPlaces(t);
  body.innerHTML = '';
  if (t.guide && Array.isArray(t.guide.guides) && t.guide.guides.length) {
    renderGuides(body, t, places);
    renderGenerateForm(body, t, places, true);
  } else {
    renderGenerateForm(body, t, places, false);
  }
}

export function openDestinationGuide() {
  const t = activeTrip();
  if (!t) return;

  const bg = el('div', { class: 'vp-modal-bg', onclick: e => { if (e.target === bg) bg.remove(); } });
  const m = el('div', { class: 'vp-modal vp-dg-modal' });
  m.appendChild(el('h3', {}, 'Destination guide'));
  const body = el('div', { class: 'vp-dg-body' });
  m.appendChild(body);

  const actions = el('div', { class: 'vp-modal-actions' });
  actions.appendChild(el('div', {}));
  const right = el('div', { class: 'vp-right' });
  right.appendChild(el('button', { onclick: () => bg.remove() }, 'Close'));
  actions.appendChild(right);
  m.appendChild(actions);

  bg.appendChild(m);
  document.body.appendChild(bg);

  const places = tripPlaces(t);
  if (!places.length) {
    body.appendChild(el('p', { class: 'vp-tc-empty' },
      'Add some cards or places with cities first — the guide needs to know where you are going.'));
    return;
  }
  renderOpen(body, t);
}
